apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: blobnfs-pvc-read-write-demo
spec:
  accessModes:
  - ReadWriteOnce
  storageClassName: blob-nfs
  resources:
    requests:
      storage: 5Gi
