apiVersion: v1
kind: Namespace
metadata:
  name: sftp
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv-blob
spec:
  capacity:
    storage: 10Gi
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain  # If set as "Delete" container would be removed after pvc deletion
  storageClassName: azureblob-nfs-premium
  csi:
    driver: blob.csi.azure.com
    readOnly: false
    # make sure this volumeid is unique in the cluster
    # `#` is not allowed in self defined volumeHandle
    volumeHandle: 162f598b-6895-44cb-9994-021cdf282808
    volumeAttributes:
      resourceGroup: KubeConBlobDemo
      storageAccount: aksblobnfsgriff87
      containerName: upload
      protocol: nfs
---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: pvc-blob
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 10Gi
  volumeName: pv-blob
  storageClassName: azureblob-nfs-premium

---
kind: Service
apiVersion: v1
metadata:
  name: sftp
  namespace: sftp
spec:
  type: LoadBalancer
  ports:
  - name: "ssh"
    port: 22
    targetPort: 22
  selector:
    app: sftp
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: sftp
  name: sftp
  namespace: sftp
spec:
  replicas: 1
  selector:
    matchLabels:
      app: sftp
  template:
    metadata:
      labels:
        app: sftp
    spec:
      initContainers:
      - name: setup
        image: busybox:latest
        command: ["/bin/sh"]
        args: ['-c','echo "aksuser:reddog9876:::upload">/etc/sftp/users.conf']
        volumeMounts:
        - name: sftpconfig
          mountPath: /etc/sftp
      containers:
      - image: atmoz/sftp:latest
        name: sftp
        ports:
        - containerPort: 22
        volumeMounts:
        - name: sftpconfig
          mountPath: /etc/sftp
        - name: blobnfs
          mountPath: /home/aksuser/upload
      volumes:
      - name: sftpconfig
        emptyDir: {}
      - name: blobnfs
        persistentVolumeClaim:
          claimName: pv-blob
