apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: dd-demo
  name: dd-demo
spec:
  replicas: 10
  selector:
    matchLabels:
      app: dd-demo
  template:
    metadata:
      labels:
        app: dd-demo
    spec:
      containers:
      - image: ubuntu
        name: ubuntu
        command: [ "/bin/bash", "-c", "--" ]
        args: [ "while true; do dd if=/dev/urandom of=/blobnfs/${RANDOM}.dat 
bs=1M count=10000; sleep 20; done;" ]
        volumeMounts:
            - mountPath: /blobnfs
              name: blobnfs
      volumes:
        - name: blobnfs
          persistentVolumeClaim:
            claimName: pvc-blob
